theme = "onedark"

editor.shell = ["nu", "-c"]
editor.gutters = []
editor.auto-format = false
editor.continue-comments = false
editor.popup-border = "all"
editor.auto-save.focus-lost = true
editor.completion-replace = true
editor.end-of-line-diagnostics = "warning"
editor.search.smart-case = false
editor.search.wrap-around = false
editor.completion-timeout = 5
editor.completion-trigger-len = 1
