theme = "nord"

editor.shell = ["nu", "-c"]
editor.gutters = []
editor.auto-format = false
editor.continue-comments = false
editor.popup-border = "all"
editor.inline-diagnostics.cursor-line = "warning"
editor.inline-diagnostics.other-lines = "warning"
editor.auto-save.focus-lost = true
editor.completion-replace = true
editor.search.smart-case = false
editor.search.wrap-around = false
