[language-server.redpen]
command = "redpen.py"

[[language]]
name = "text"
scope = "source.text"
file-types = ["txt", "md"]
soft-wrap.enable = true
language-servers = ["redpen"]

[[language]]
name = "python"
language-servers = ["pyright"]
