#!/bin/sh

export SCRIPT="~/.config/scripts"

dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP XDG_SESSION_TYPE
river-bsp-layout --reverse &
waybar &

riverctl map -repeat -layout 0 normal Super               Q         close
riverctl map -repeat -layout 0 normal Super+Shift         Q         spawn "systemctl suspend"
riverctl map -repeat -layout 0 normal Super               D         spawn "$SCRIPT/volume.nu SINK -"
riverctl map -repeat -layout 0 normal Super               R         spawn "$SCRIPT/volume.nu SINK +"
riverctl map -repeat -layout 0 normal Super               W         spawn "$SCRIPT/bluetooth.nu"
riverctl map -repeat -layout 0 normal Super+Shift         D         spawn "$SCRIPT/brightness.nu -"
riverctl map -repeat -layout 0 normal Super+Shift         R         spawn "$SCRIPT/brightness.nu +"
riverctl map -repeat -layout 0 normal Super+Control       D         spawn "$SCRIPT/volume.nu SOURCE -"
riverctl map -repeat -layout 0 normal Super+Control       R         spawn "$SCRIPT/volume.nu SOURCE +"

riverctl map -repeat -layout 0 normal Super               A         spawn "xdg-terminal-exec"
riverctl map -repeat -layout 0 normal Super               S         spawn "chromium"
riverctl map -repeat -layout 0 normal Super+Shift         S         spawn "chromium --incognito"
riverctl map -repeat -layout 0 normal Super               H         toggle-fullscreen
riverctl map -repeat -layout 0 normal Super+Shift         H         toggle-float
riverctl map -repeat -layout 0 normal Super               T         spawn "$SCRIPT/screenshot.nu copyarea"
riverctl map -repeat -layout 0 normal Super+Shift         T         spawn "$SCRIPT/screenshot.nu savearea"
riverctl map -repeat -layout 0 normal Super+Control       T         spawn "$SCRIPT/screenshot.nu copyscreen"
riverctl map -repeat -layout 0 normal Super+Control+Shift T         spawn "$SCRIPT/screenshot.nu savescreen"

riverctl map -repeat -layout 0 normal Super               Z         set-focused-tags    1
riverctl map -repeat -layout 0 normal Super+Shift         Z         set-view-tags       1
riverctl map -repeat -layout 0 normal Super+Control       Z         toggle-focused-tags 1
riverctl map -repeat -layout 0 normal Super+Control+Shift Z         toggle-view-tags    1
riverctl map -repeat -layout 0 normal Super               X         set-focused-tags    2
riverctl map -repeat -layout 0 normal Super+Shift         X         set-view-tags       2
riverctl map -repeat -layout 0 normal Super+Control       X         toggle-focused-tags 2
riverctl map -repeat -layout 0 normal Super+Control+Shift X         toggle-view-tags    2
riverctl map -repeat -layout 0 normal Super               M         set-focused-tags    4
riverctl map -repeat -layout 0 normal Super+Shift         M         set-view-tags       4
riverctl map -repeat -layout 0 normal Super+Control       M         toggle-focused-tags 4
riverctl map -repeat -layout 0 normal Super+Control+Shift M         toggle-view-tags    4
riverctl map -repeat -layout 0 normal Super               C         set-focused-tags    8
riverctl map -repeat -layout 0 normal Super+Shift         C         set-view-tags       8
riverctl map -repeat -layout 0 normal Super+Control       C         toggle-focused-tags 8
riverctl map -repeat -layout 0 normal Super+Control+Shift C         toggle-view-tags    8

riverctl map -repeat -layout 0 normal Super               Left      focus-view -skip-floating left
riverctl map -repeat -layout 0 normal Super               Right     focus-view -skip-floating right
riverctl map -repeat -layout 0 normal Super               Up        focus-view -skip-floating up
riverctl map -repeat -layout 0 normal Super               Down      focus-view -skip-floating down
riverctl map -repeat -layout 0 normal Super+Shift         Left      swap                      left
riverctl map -repeat -layout 0 normal Super+Shift         Right     swap                      right
riverctl map -repeat -layout 0 normal Super+Shift         Up        swap                      up
riverctl map -repeat -layout 0 normal Super+Shift         Down      swap                      down

riverctl map -repeat -layout 0 normal Super               Space     spawn "playerctl play-pause"

riverctl map-pointer           normal Super               BTN_LEFT  move-view
riverctl map-pointer           normal Super               BTN_RIGHT resize-view

riverctl rule-add -title 'Picture in picture' float
riverctl rule-add -title 'Picture in picture' position 2560 1440
riverctl rule-add                             ssd

riverctl border-width 0
riverctl set-repeat 60 300
riverctl focus-follows-cursor normal
riverctl set-cursor-warp on-focus-change
riverctl keyboard-layout -options grp:alt_space_toggle us,fi
riverctl input "*" tap enabled
riverctl input "*" disable-while-typing disabled
riverctl input "pointer-1267-47-Elan_Touchpad" natural-scroll enabled
riverctl default-layout bsp-layout
