inherits = "jetbrains_dark"

"ui.background" = { fg = "blue196", bg = "blueBG" }
"ui.statusline.insert" = { fg = "blue196", bg = "blueHL" }
"ui.statusline.normal" = { fg = "blue196", bg = "blue48" }
"ui.statusline.select" = { fg = "blue196", bg = "blue48" }
"ui.statusline.active" = { fg = "blue196", bg = "blueHL" }
"ui.statusline.inactive" = { fg = "blue196", bg = "blue48" }
"ui.gutter.selected" = { fg = "blue56" }

[palette]
blueBG = "#1f1f1f"
blueHL = "#454545"
blue34 = "#212121"
blue46 = "#2e2e2e"
blue48 = "#303030"
blue50 = "#333333"
blue56 = "#383838"
blue81 = "#525252"
blue89 = "#595959"
blue122 = "#7a7a7a"
blue133 = "#858585"
blue145 = "#919191"
blue171 = "#ababab"
blue196 = "#c4c4c4"
# blue64 = "#404040"
# blue110 = "#6e6e6e"
# blue131 = "#828282"
# blue173 = "#adadad"
# blue184 = "#b8b8b8"
# blue245 = "#f5f5f5"
# blue247 = "#f7f7f7"
