theme = "nord"

[editor.statusline]
left = ["mode", "file-name", "read-only-indicator", "file-modification-indicator"]

[editor.search]
wrap-around = false

[editor]
color-modes = true
shell = ["nu", "-c"]
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
auto-format = false

[editor.auto-save]
focus-lost = true
