theme = "nord"

[editor.search]
smart-case = false
wrap-around = false

[editor]
color-modes = true
shell = ["nu", "-c"]
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
auto-format = false
line-number = "relative"
continue-comments = false
clipboard-provider = "termcode"

[editor.auto-save]
focus-lost = true
