theme = "base16_transparent"

[keys.normal]
C-m = "toggle_comments"

[keys.select]
C-m = "toggle_comments"

[editor.statusline]
left        = ["mode"]
right       = ["diagnostics"]
mode.normal = "    "
mode.insert = "    "
mode.select = "    "

[editor.search]
wrap-around = false

[editor]
scrolloff              = 0
true-color             = true
gutters                = ["diff", "diagnostics", "spacer", "line-numbers", "spacer"]
bufferline             = "always"
color-modes            = true
completion-replace     = true
completion-trigger-len = 1
idle-timeout           = 0

[editor.cursor-shape]
insert = "bar"

[editor.whitespace.render]
tab = "all"
