theme = "adwaita-dark" #fleet_dark adwaita-dark rasmus

[keys.insert]
S-tab = "unindent"
C-right = "move_next_word_start"
C-left = "move_prev_word_start"

[keys.normal]
C-s = ":w!"
C-w = ":bc!"
C-q = ":q!"
S-tab = "goto_next_buffer"
A-X = "extend_to_line_bounds"
X = "extend_line_up"
C-right = "move_next_word_start"
C-left = "move_prev_word_start"

[keys.select]
A-X = "extend_to_line_bounds"
X = "extend_line_up"
C-right = "move_next_word_start"
C-left = "move_prev_word_start"

[editor.statusline]
left = ["mode", "file-base-name", "file-modification-indicator"]
right = ["position"]
mode.normal = ""
mode.insert = ""
mode.select = ""

[editor.file-picker]
hidden = false
follow-symlinks = false

[editor.indent-guides]
render = true
character = "⸽"

[editor]
scroll-lines = 2
# scroll-lines = 6
line-number = "relative"
color-modes     = true
bufferline = "multiple"
scrolloff = 0
idle-timeout = 0
completion-trigger-len = 1
completion-replace = true
cursorline = true
preview-completion-insert       = false

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"

[editor.search]
wrap-around = false

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer", "spacer"]

[editor.smart-tab]
supersede-menu = true
