theme = "nord"

[editor.statusline]
left = ["mode", "file-name", "file-modification-indicator"]
center = ["diagnostics"]
right = ["selections", "position"]

[editor.search]
wrap-around = false

[editor]
color-modes = true
scrolloff = 0
shell = ["nu", "-c"]
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.soft-wrap]
wrap-indicator = ""

[editor.auto-save]
focus-lost = true
