theme = "monokai_pro"

[keys.select]
C-S-c = "toggle_comments"

[keys.normal]
C-S-c = "toggle_comments"

[editor.statusline]
left = ["file-modification-indicator", "file-base-name"]
center = ["diagnostics"]
right = ["selections"]

[editor.cursor-shape]
insert = "bar"

[editor.search]
wrap-around = false

[editor]
completion-replace = true
scrolloff = 1
gutters = ["diff", "diagnostics", "spacer", "line-numbers", "spacer"]
auto-format = false
auto-save = true

[editor.lsp]
display-inlay-hints = true

[editor.whitespace.render]
tab = "all"
