theme = "monokai_pro"

[editor.statusline]
left = ["mode", "file-name", "file-modification-indicator"]
center = ["diagnostics"]
right = ["position", "total-line-numbers"]

[editor.search]
wrap-around = false

[editor]
color-modes = true
scrolloff = 3
shell = ["nu", "-c"]
completion-timeout = 0
completion-trigger-len = 1
auto-format = false
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.soft-wrap]
wrap-indicator = ""

[editor.auto-save]
focus-lost = true
