theme = "adwaita-dark-fix"

[editor.statusline]
left = []
center = []
right = []

[editor.cursor-shape]
insert = "bar"

[editor.search]
wrap-around = false

[editor]
completion-replace = true
scrolloff = 1
auto-format = false
true-color = true
bufferline = "always"

[editor.file-picker]
hidden = false

[editor.gutters]
layout = ["diff", "line-numbers", "spacer"]

[editor.gutters.line-numbers]
min-width = 4
