theme = "monokai_pro"

[keys.select]
C-S-c = "toggle_comments"

[keys.normal]
C-S-c = "toggle_comments"

[editor.statusline]
left = ["file-absolute-path", "spacer", "version-control"]
center = ["workspace-diagnostics", "diagnostics"]
right = ["position", "total-line-numbers", "primary-selection-length", "selections", "mode"]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[editor.cursor-shape]
insert = "bar"

[editor.search]
wrap-around = false

[editor]
scrolloff = 0
true-color = true
gutters = ["diff", "diagnostics", "spacer", "line-numbers", "spacer"]
bufferline = "always"

[editor.whitespace.render]
tab = "all"
