theme = "nord"

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode", "file-name", "read-only-indicator", "file-modification-indicator"]

[editor.search]
wrap-around = false

[editor]
shell = ["nu", "-c"]
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.auto-save]
focus-lost = true
