theme = "nord-fix"

[editor.statusline]
left = ["mode", "file-absolute-path"]
center = ["diagnostics"]
right = ["position", "primary-selection-length", "selections", "total-line-numbers"]

[editor.search]
wrap-around = false

[editor]
completion-replace = true
scrolloff = 0
auto-format = false
bufferline = "always"
color-modes = true

[editor.gutters]
layout = ["diff", "line-numbers", "spacer"]

[editor.gutters.line-numbers]
min-width = 4
