theme = "jetbrains_dark_fix"

[editor.statusline]
left = ["file-base-name", "file-modification-indicator"]
center = ["diagnostics"]
right = ["position", "total-line-numbers"]

[editor.search]
wrap-around = false

[editor]
scrolloff = 3
scroll-lines = 1
shell = ["nu", "-c"]
idle-timeout = 0
completion-timeout = 0
completion-trigger-len = 1
completion-replace = true
auto-format = false
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.cursor-shape]
insert = "bar"

[editor.smart-tab]
supersede-menu = true

[editor.auto-save]
focus-lost = true
