theme = "nord-fix"

[editor.statusline]
left = ["file-absolute-path", "version-control"]
center = ["diagnostics"]
right = ["position", "primary-selection-length", "selections", "total-line-numbers"]

[editor.cursor-shape]
insert = "bar"

[editor.search]
wrap-around = false

[editor]
completion-replace = true
scrolloff = 0
auto-format = false
bufferline = "always"

[editor.gutters]
layout = ["diff", "line-numbers", "spacer"]

[editor.gutters.line-numbers]
min-width = 4
