# https://download.eclipse.org/jdtls/milestones/1.30.0/

[language-server.jdtls]
command = "jdtls"
args = [ 
  "-configuration", "/home/user/.cache/jdtls/config",
  "-data", "/home/user/.cache/jdtls/workspace"
]
  
[[language]]
name = "java"
scope = "source.java"
injection-regex = "java"
file-types = ["java"]
roots = ["build.xml", "pom.xml", "settings.gradle", "settings.gradle.kts"]
language-servers = ["jdtls"]
